  version: '3.8'
  services:
    postgres:
      image: postgres:17-alpine
      container_name: booking_db
      ports:
        - "5435:5432"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: booking_platform

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_gui
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
      ports:
          - "5051:80"
      depends_on:
          - postgres
    redis:
      image: redis:7-alpine
      container_name: cache_lock
      ports:
        - "6380:6379"

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: broker
      ports:
        - "5672:5672"