// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: booking.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "booking";

/** ----- Generic ----- */
export interface Empty {
}

/** ----- Admin: Create Event ----- */
export interface CreateEventRequest {
  name: string;
  /** ISO 8601 string */
  date: string;
  totalCapacity: number;
  basePrice: number;
  artist: string;
  description: string;
  venue: string;
  image: string;
}

export interface CreateEventResponse {
  eventId: string;
  message: string;
}

/** ----- Public: Fetch Events ----- */
export interface EventSummary {
  id: string;
  name: string;
  date: string;
  availableTickets: number;
  artist: string;
  venue: string;
  image: string;
  totalCapacity: number;
}

export interface GetEventsResponse {
  events: EventSummary[];
}

/** ----- Public: Event Details & Seats ----- */
export interface SeatDTO {
  id: string;
  seatNumber: string;
  /** AVAILABLE, RESERVED, SOLD */
  status: string;
  price: number;
}

export interface GetEventDetailsRequest {
  eventId: string;
}

export interface GetEventDetailsResponse {
  id: string;
  name: string;
  date: string;
  seats: SeatDTO[];
}

/** ----- Transactions: Reservations & Booking ----- */
export interface ReserveSeatRequest {
  eventId: string;
  /** Changed from seat_id to align with DB schema */
  ticketId: string;
  userId: string;
}

export interface ReserveSeatResponse {
  success: boolean;
  reservationId: string;
  expiresAt: string;
  message: string;
}

export interface ConfirmBookingRequest {
  reservationId: string;
  paymentId: string;
  userId: string;
}

export interface ConfirmBookingResponse {
  success: boolean;
  orderId: string;
  status: string;
  message: string;
}

export const BOOKING_PACKAGE_NAME = "booking";

export interface BookingServiceClient {
  /** Admin Endpoints */

  createEvent(request: CreateEventRequest): Observable<CreateEventResponse>;

  /** Public Endpoints */

  getEvents(request: Empty): Observable<GetEventsResponse>;

  getEventDetails(request: GetEventDetailsRequest): Observable<GetEventDetailsResponse>;

  /** Transactional Endpoints */

  reserveSeat(request: ReserveSeatRequest): Observable<ReserveSeatResponse>;

  confirmBooking(request: ConfirmBookingRequest): Observable<ConfirmBookingResponse>;
}

export interface BookingServiceController {
  /** Admin Endpoints */

  createEvent(
    request: CreateEventRequest,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  /** Public Endpoints */

  getEvents(request: Empty): Promise<GetEventsResponse> | Observable<GetEventsResponse> | GetEventsResponse;

  getEventDetails(
    request: GetEventDetailsRequest,
  ): Promise<GetEventDetailsResponse> | Observable<GetEventDetailsResponse> | GetEventDetailsResponse;

  /** Transactional Endpoints */

  reserveSeat(
    request: ReserveSeatRequest,
  ): Promise<ReserveSeatResponse> | Observable<ReserveSeatResponse> | ReserveSeatResponse;

  confirmBooking(
    request: ConfirmBookingRequest,
  ): Promise<ConfirmBookingResponse> | Observable<ConfirmBookingResponse> | ConfirmBookingResponse;
}

export function BookingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createEvent", "getEvents", "getEventDetails", "reserveSeat", "confirmBooking"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BookingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BookingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BOOKING_SERVICE_NAME = "BookingService";
