// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: booking.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "booking";

export interface ReserveSeatRequest {
  eventId: string;
  seatId: string;
  userId: string;
}

export interface ReserveSeatResponse {
  success: boolean;
  reservationId: string;
  expiresAt: string;
}

export interface ConfirmBookingRequest {
  reservationId: string;
  paymentId: string;
}

export interface ConfirmBookingResponse {
  orderId: string;
  status: string;
}

export const BOOKING_PACKAGE_NAME = "booking";

export interface BookingServiceClient {
  reserveSeat(request: ReserveSeatRequest): Observable<ReserveSeatResponse>;

  confirmBooking(request: ConfirmBookingRequest): Observable<ConfirmBookingResponse>;
}

export interface BookingServiceController {
  reserveSeat(
    request: ReserveSeatRequest,
  ): Promise<ReserveSeatResponse> | Observable<ReserveSeatResponse> | ReserveSeatResponse;

  confirmBooking(
    request: ConfirmBookingRequest,
  ): Promise<ConfirmBookingResponse> | Observable<ConfirmBookingResponse> | ConfirmBookingResponse;
}

export function BookingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["reserveSeat", "confirmBooking"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BookingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BookingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BOOKING_SERVICE_NAME = "BookingService";
